CREATE TABLE Users(
  user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  rule VARCHAR(255) NOT NULL,
  PRIMARY KEY(user_id)
);

INSERT INTO 
	Users (username, password, rule)
VALUES
	('user', 'user', 'user'),
	('admin', 'admin', 'admin');
