CREATE TABLE Library(
  library_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  create_time DATE NOT NULL,
  update_time DATE NOT NULL,
  PRIMARY KEY(library_id)
);

CREATE TABLE Renters( 
  renter_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  create_time DATE NOT NULL,
  update_time DATE NOT NULL,
  library_id INT NOT NULL,
  
  PRIMARY KEY(renter_id),
  CONSTRAINT fk_library
    FOREIGN KEY(library_id)
    REFERENCES Library(library_id) ON DELETE CASCADE
);

CREATE TABLE Books(
  book_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
  author VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  create_time DATE NOT NULL,
  update_time DATE NOT NULL,
  library_id INT NOT NULL,
  renter_id INT NOT NULL,
  PRIMARY KEY(book_id),
  CONSTRAINT fk_library
    FOREIGN KEY(library_id)
    REFERENCES Library(library_id) ON DELETE CASCADE,
  CONSTRAINT fk_renter 	
    FOREIGN KEY(renter_id) 
    REFERENCES Renters(renter_id) ON DELETE CASCADE
);
